// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tUserFieldNames          = builder.RawFieldNames(&TUser{})
	tUserRows                = strings.Join(tUserFieldNames, ",")
	tUserRowsExpectAutoSet   = strings.Join(stringx.Remove(tUserFieldNames, "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	tUserRowsWithPlaceHolder = strings.Join(stringx.Remove(tUserFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheZeroDemoTUserIdPrefix = "cache:zeroDemo:tUser:id:"
)

type (
	tUserModel interface {
		Insert(ctx context.Context, data *TUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TUser, error)
		Update(ctx context.Context, data *TUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTUserModel struct {
		sqlc.CachedConn
		table string
	}

	TUser struct {
		Id       int64  `db:"id"`
		UserId   int64  `db:"user_id"`
		NickName string `db:"nick_name"`
	}
)

func newTUserModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultTUserModel {
	return &defaultTUserModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`t_user`",
	}
}

func (m *defaultTUserModel) Delete(ctx context.Context, id int64) error {
	zeroDemoTUserIdKey := fmt.Sprintf("%s%v", cacheZeroDemoTUserIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroDemoTUserIdKey)
	return err
}

func (m *defaultTUserModel) FindOne(ctx context.Context, id int64) (*TUser, error) {
	zeroDemoTUserIdKey := fmt.Sprintf("%s%v", cacheZeroDemoTUserIdPrefix, id)
	var resp TUser
	err := m.QueryRowCtx(ctx, &resp, zeroDemoTUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tUserRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTUserModel) Insert(ctx context.Context, data *TUser) (sql.Result, error) {
	zeroDemoTUserIdKey := fmt.Sprintf("%s%v", cacheZeroDemoTUserIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, tUserRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.NickName)
	}, zeroDemoTUserIdKey)
	return ret, err
}

func (m *defaultTUserModel) Update(ctx context.Context, data *TUser) error {
	zeroDemoTUserIdKey := fmt.Sprintf("%s%v", cacheZeroDemoTUserIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tUserRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.NickName, data.Id)
	}, zeroDemoTUserIdKey)
	return err
}

func (m *defaultTUserModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheZeroDemoTUserIdPrefix, primary)
}

func (m *defaultTUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tUserRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTUserModel) tableName() string {
	return m.table
}
