// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "go-zero-single-demo/greet/internal/handler/user"
	"go-zero-single-demo/greet/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from",
				Handler: user.GreetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: user.GreetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/save",
				Handler: user.GreetUserRegisterHandler(serverCtx),
			},
		},
	)
}
