// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `json:"name"`
}

type Response struct {
	Message string `json:"message"`
}

type UserInfoRequest struct {
	Id string `path:"id"`
}

type UserInfoResponse struct {
	Id             string `json:"id"`
	Name           string `json:"name"`
	Age            int    `json:"age"`
	Address        string `json:"address"`
	AddressInfo    string `json:"nnn"`
	AaaaddressInfo string `json:"nnnddd"`
}

type UserRegisterRequest struct {
	Id      string `form:"id"`
	Name    string `form:"name"`
	Age     int    `form:"age"`
	Address string `form:"address"`
}
